### ISSUE TITLE
compiling coreutils-8.30 using clang-6.0 in x86_64 using O2 meets "linker" error

### ISSUE THREAD

**Issue by island255** [SoftSec-KAIST/BinKit#3]
Hi, I am trying to compile Coreutils-8.30 using clang-6.0 in x86_64 using O2, but meet errors. The log file **coreutils-8.30_clang-6.0_x86_64_O2_normal_CCTARGET_AUTO_install_error.log** writes that:

_lib/libcoreutils.a(randint.o): In function `explicit_bzero':
/root/tools//x86_64-ubuntu-linux-gnu-8.2.0/x86_64-ubuntu-linux-gnu/sysroot/usr/include/bits/string_fortified.h:83: undefined reference to `__explicit_bzero_chk'
/root/tools//x86_64-ubuntu-linux-gnu-8.2.0/x86_64-ubuntu-linux-gnu/sysroot/usr/include/bits/string_fortified.h:83: undefined reference to `__explicit_bzero_chk'
lib/libcoreutils.a(randread.o): In function `explicit_bzero':
/root/tools//x86_64-ubuntu-linux-gnu-8.2.0/x86_64-ubuntu-linux-gnu/sysroot/usr/include/bits/string_fortified.h:83: undefined reference to `__explicit_bzero_chk'
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/cp] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2_

Do you know how to solve this problem? Waiting for your reply.

**Comment by 0xdkay** [comment]
Hi, I've been working on other issues, coming back quite late.
I haven't seen such an issue. Could you describe your execution environment and when this issue occurred? 
Could you confirm that you installed [dependencies](https://github.com/SoftSec-KAIST/BinKit/blob/master/scripts/install_gnu_deps.sh)?

**Comment by island255** [comment]
Yes, I have run this script to install the dependencies. Although some packages are not installed such as libtoolize and libtoolize-dev, I think I already have enough packages as I can successfully compile coreutils-8.30 using clang-6.0 in x86_64 using O0. 

This problem occurs when I try to compile with O1-Os. And I have been searching this problem and found that this problem may be related to the version of glibc. And I am using the pre-compiled toolchain and find this clang environment refers to x86_64-ubuntu-linux-gnu-8.2.0. But I am not familiar with this environment, so it is hard for me to fix it.

If you can check whether there is a problem in this environment, I will be very grateful.

**Comment by 0xdkay** [comment]
By compiling multiple times, I found that compilation successfully works depending on the name of the configuration file (~.yml). The failure case seems similar to your issue, and I'm currently working on it.

**Comment by island255** [comment]
Thanks for your hard works！ Waiting for the good news!

**Comment by 0xdkay** [comment]
There was a remaining command line for debugging and I removed it. Please check the new version and let me know if the problem still exists.

**Comment by island255** [comment]
I have tried this new version. And almost all problems are solved. But I see some new problems here.

One thing is that when I try to compile coreutils 8.32 at x86-64 using clang -O1 to -O3, an error occurs as _aclocal-1.16: command not found_

I have searched this problem and it may be caused by the timestamp. It may be special to this project.

And another thing is that when I try to run gnu_compile_script.py or compile_checker.py, it seems to cannot find there is an error occurred during compilation. 

Apart from these two things, the common errors that occurred before have been solved. Thanks for your help again!

**Comment by 0xdkay** [comment]
I re-checked this problem and found that the current fix did not fix the bug correctly. The issue is caused by [line 337](https://github.com/SoftSec-KAIST/BinKit/blob/master/do_compile_utils.sh#L337), which eventually trigger [line 350](https://github.com/SoftSec-KAIST/BinKit/blob/master/do_compile_utils.sh#L350) to filter out compiled binaries if the name of the config file contains "test" (which is included in the directory of source files when compiling). I marked the command line including "prefix" as for debug, but I remembered that I intentionally used it to consider only compiled output binaries instead of auxiliary binaries. In the next commit, I will revert this to include the "prefix" command line and add descriptions not to include "test" as the name of the config file name.

**Comment by island255** [comment]
Actually, I don't know how this problem is fixed. Sometimes I just use the normal.yml and change its content, the compilation may also fail. I don't know if it is because of the "--prefix" in "configure", but this time many compilations just succeed. 

I don't know if it is right to remove "test" binaries. Sometimes some "test" binary is not what we want, but sometimes we just include it as part of the dataset for binary similarity analysis, such as "[" in coreutils compiled by test.c in src. So in my opinion, an option for whether to produce "test" binaries may be better.

**Comment by 0xdkay** [comment]
Thanks for your suggestion. I made that the compilation script do not filter out a compiled binary named "test". As you said, filtering the other test binaries can be an option, but as far as I checked, the test binaries are often not related to the target package and even their architecture does not match with the target architecture. I guess these test binaries are for testing the host (i.e., build) system. To improve the filtering, instead of using only the file name, it would be nice to check both the file name and format (for architecture) of output binaries.

BTW, I fixed two bugs:
(1) Invalid base directory set up in `compile_checker.py`. This was fixed by 70c786e.
(2) Filtering configuration file named "test" in `do_compile_utils.sh`. This was fixed by 2855186.

Please let me know if you have any other issues.
